### PR TITLE
intellij: fix narrowing

### LINKED ISSUE #103: add tests for intellij plugin

### LINKED ISSUE #109: IntelliJ: Support 2024.1
probs when it hits beta

### PR DESCRIPTION
**Pull request by KotlinIsland**
\+ px
\+ tests
\+ upgradle
\+ support 2024.1

- resolves: #109
- resolves: #103

### CODE REVIEW

File: intellij/src/test/java/com/jetbrains/python/PythonMockSdk.java [hunk 1]
```diff
@@ -0,0 +1,128 @@
+// Copyright 2000-2021 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
+package com.jetbrains.python;
```
Comment (DetachHead) [inline intellij/src/test/java/com/jetbrains/python/PythonMockSdk.java:2]: vendored?

File: intellij/src/test/java/com/jetbrains/python/README.md [hunk 2]
```diff
@@ -0,0 +1 @@
+This stuff is copied from JetBrains/intellij-community because they don't shit it
```
Comment (DetachHead) [inline intellij/src/test/java/com/jetbrains/python/README.md]: 😳

File: pw
Comment (DetachHead) [inline pw:1]: update everything that uses poetry to use pw
